version: '3.8'
services:
    # MongoDB
    mongo:
        container_name: mongodb
        image: mongo:5.0
        env_file:
            - .env
        ports: 
            - "27017:27017"
    mongo-express:
        image: mongo-express:1.0.0-alpha
        environment: 
          - ME_CONFIG_MONGODB_SERVER=mongo
          - ME_CONFIG_MONGODB_ADMINUSERNAME=root
          - ME_CONFIG_MONGODB_ADMINPASSWORD=example
          - ME_CONFIG_BASICAUTH_USERNAME=root
          - ME_CONFIG_BASICAUTH_PASSWORD=example
        depends_on:
            - mongo
        ports:
          - "8081:8081"
   # Initial Seed to Restaurants Database
    mongo-seed:
        env_file:
            - .env
        build:
            context: ./mongo_seed
            dockerfile: Dockerfile
            args:
                - DATABASE_URI=$DATABASE_URI
                - USERNAME=$MONGO_INITDB_ROOT_USERNAME
                - PASSWORD=$MONGO_INITDB_ROOT_PASSWORD
        depends_on:
            - mongo


